version: "2"
services:
    web:
        tty: true
        stdin_open: true
        build: .
        volumes:
            - ./:/app
        ports:
            - "3000:3000"
            - "9229:9229"
        links:
            - mongo
        environment:
            - MY_ENV_VAR="some value"
    mongo:
        image: mongo
        ports:
            - "27018:27017"
